### ISSUE TITLE
Pesquisa - OCR

### ISSUE THREAD

**Issue by Hargre** [fga-eps-mds/PDF2Knowledge#13]
- Pesquisar e avaliar as tecnologias existentes para Reconhecimento Óptico de Caracteres (OCR), de acordo com o contexto do projeto.
- Relatar os resultados, de forma a gerar base teórica para tomada de decisões.

**Comment by lucasdutraf** [comment]
Achei os seguintes links, sendo o terceiro o mais interessante entre todos:
https://techtalk.gfi.com/ocr-integrate-faxing/
http://www.legalscans.com/ocr.html
https://www.explainthatstuff.com/how-ocr-works.html
https://www.youtube.com/watch?v=jO-1rztr4O0
https://www.youtube.com/watch?v=gHpTADgF8c8
http://www.how-ocr-works.com/OCR/OCR.html

**Comment by Jacoapolinario** [comment]
Não sei se já viram esse link, ele já da uma boa ideia do assunto em python
http://pythonclub.com.br/extraindo-texto-de-imagens-com-python.html

**Comment by EsioFreitas** [comment]
Time, encontrei esses artigos bem interessantes! 
https://medium.com/@MicroPyramid/extract-text-with-ocr-for-all-image-types-in-python-using-pytesseract-ec3c53e5fc3a
https://www.pyimagesearch.com/2017/07/10/using-tesseract-ocr-python/
https://medium.com/@winston.smith.spb/python-ocr-for-pdf-or-compare-textract-pytesseract-and-pyocr-acb19122f38c

**Comment by Hargre** [comment]
Algumas libs em cima do Tesseract, em várias linguagens:
* https://github.com/tesseract-ocr/tesseract (A original, em C++)
* https://github.com/charlesw/tesseract (.NET, não é atualizada faz uns anos)
* https://github.com/madmaze/pytesseract (Python)
* http://tesseract.projectnaptha.com/ (Implementação inteira em JavaScript, tem uma live demo no site)


E uma lista imensa de plugins e ferramentas na wiki original: https://github.com/tesseract-ocr/tesseract/wiki/AddOns
