### ISSUE TITLE
Pesquisa - Manipulação de PDFs em código

### ISSUE THREAD

**Issue by Hargre** [fga-eps-mds/PDF2Knowledge#14]
- Avaliar ferramentas e linguagens disponíveis.
- Estudar a estrutura interna de um PDF.
- Desenvolver mini-aplicações com as ferramentas descobertas para exercitar a manipulação de arquivos.

**Comment by devsalula** [comment]
Achei algumas bibliotecas:
Biblioteca para extrair texto de PDF's: https://textract.readthedocs.io/en/stable/index.html
Biblioteca para extrair texto de Imagens: https://github.com/madmaze/pytesseract

**Comment by Phe0** [comment]
Manipulação de PDFs usando Python:
https://reachtim.com/articles/PDF-Manipulation.html

**Comment by Phe0** [comment]
Navegação na estrutura interna do PDF:
http://www.planetpdf.com/developer/article.asp?ContentID=navigating_the_internal_struct&page=1

**Comment by Phe0** [comment]
Esse link é bem explicativo, possui um exemplo de PDF q é explicado em detalhes:
https://web.archive.org/web/20141010035745/http://gnupdf.org/Introduction_to_PDF

**Comment by lucasdutraf** [comment]
Achei essa [biblioteca](https://github.com/pmaupin/pdfrw#introduction) que é bastante citada em tutoriais inclusive [nesse](https://bostata.com/post/how_to_populate_fillable_pdfs_with_python/).

**Comment by lucasdutraf** [comment]
OpenCV é uma biblioteca de visão computacional e machine learning de código aberto, escrita principalmente em c++: https://github.com/opencv/opencv , li mais sobre visão computacional e pode ser bastante interessante para o assunto que vamos tratar. Segue alguns links interessantes sobre o assunto: 
https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_tutorials.html
https://opencv.org/about.html
https://github.com/opencv/opencv
https://opencv.org/
