### ISSUE TITLE
Criar Roadmap de Arquitetura

### ISSUE THREAD

**Issue by Hargre** [fga-eps-mds/PDF2Knowledge#20]

**Comment by EsioFreitas** [comment]
Time, o Google tem uma lib de gráficos. Segue o link: 
https://developers.google.com/chart/

**Comment by MarianaPicolo** [comment]
![arquiteto roadmap](https://user-images.githubusercontent.com/26073710/48667975-be7d2a00-eac9-11e8-892e-ea20c7c1aadc.png)
