### ISSUE TITLE
Refinar Documento de Visão

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/PDF2Knowledge#31]
## Refinar Documento de Visão   

- MDS deve corrigir e melhorar o Documento de Visão de acordo com o feedback recebido de EPS.
- MDS deve estar alinhado com o PM para finalizar o documento.

### Tasks:
- [x] Validar com PM;
- [x] Escrever em _markdown_

O documento **deve ser finalizado até dia 05/09** e será apresentado no _sprint review_.

**Comment by EsioFreitas** [comment]
@clarissalimab o doc de visão já está pronto para ser revisado

**Comment by devsalula** [comment]
Markdown, está pronto.

**Comment by MarianaPicolo** [comment]
Gostei :+1:
