### ISSUE TITLE
GitHub Pages do Projeto

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/PDF2Knowledge#33]
# GitHub Pages do Projeto

Utilizando o Docusaurus, deixar a _wiki_ disponível com os documentos já existentes.

### Tasks:
- [x] Subir _wiki_
- [x] Adicionar documentos   

A _wiki_ **deve ser apresentada até dia 05/09**.

**Comment by MarianaPicolo** [comment]
@RochaCarla pode nos dar um _feedback_ a respeito do que foi feito até agora?

**Comment by RochaCarla** [comment]
Só na R1 :P
Mas vale a pena aumentar o quadro de conhecimento para incorporar conhecimentos nos papeis e nas ferramenta/tecnicas dos papeis 

Falta:

-> analise do scrum master (data oriented) no resultado da sprint
-> colocar quais as prioridades (no contexto de melhora continua, o que vai ser melhorado nessa sprint) no planejamento
